name: CI

on:
  push:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - run: echo ${{ vars.test }}
      - run: echo ${{ vars.all_test }}
